// These are the types that make up an npmjs.org API search response.
// Generated by https://quicktype.io


export interface Objects {
    objects: Object[];
    total:   number;
    time:    string;
}

export interface Object {
    package:     Package;
    flags:       Flags;
    score:       Score;
    searchScore: number;
}

export interface Flags {
    insecure:  number;
    unstable?: boolean;
}

export interface Package {
    name:        string;
    scope:       Scope;
    version:     string;
    description: string;
    date:        string;
    links:       Links;
    publisher:   Publisher;
    maintainers: Publisher[];
    author?:     Author;
    keywords?:   string[];
}

export interface Author {
    name:   string;
    url?:   string;
    email?: string;
}

export interface Links {
    npm:         string;
    homepage?:   string;
    repository?: string;
    bugs?:       string;
}

export interface Publisher {
    username: string;
    email:    string;
}

export enum Scope {
    Anthonyjdella = "anthonyjdella",
    Jsonresume = "jsonresume",
    Unscoped = "unscoped",
}

export interface Score {
    final:  number;
    detail: Detail;
}

export interface Detail {
    quality:     number;
    popularity:  number;
    maintenance: number;
}
